version: "3.2"

services:

  geoserver:
    image: clowder/geoserver:${VERSION:-latest}
    networks:
      - clowder
#    user: "55242:17027"
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI:-amqp://guest:guest@rabbitmq/%2F}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE:-clowder}
      - REGISTRATION_ENDPOINTS=${REGISTRATION_ENDPOINTS}
      - PROXY_ON=${PROXY_ON}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_URL=${PROXY_URL}
      - GEOSERVER_USERNAME=${GEOSERVER_USERNAME:-admin}
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD:-geoserver}
      - GEOSERVER_WORKSPACE=${GEOSERVER_WORKSPACE}
      - GEOSERVER_USER=${GEOSERVER_USER:-admin}
      - GEOSERVER_URL=${GEOSERVER_URL}
    ports:
      - 8080:8080
    volumes:
      - /generated/data/mounting:/data_dir
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  clowder: